memory_lists = [
  {
    "List Name": "Anger",
    "word_1": "mad",
    "word_2": "fear",
    "word_3": "hate",
    "word_4": "rage",
    "word_5": "temper",
    "word_6": "fury",
    "word_7": "ire",
    "word_8": "wrath",
    "word_9": "happy",
    "word_10": "fight",
    "word_11": "hatred",
    "word_12": "mean",
    "word_13": "calm",
    "word_14": "emotion",
    "word_15": "enrage"
  },
  {
    "List Name": "Black",
    "word_1": "white",
    "word_2": "dark",
    "word_3": "cat",
    "word_4": "charred",
    "word_5": "night",
    "word_6": "funeral",
    "word_7": "color",
    "word_8": "grief",
    "word_9": "blue",
    "word_10": "death",
    "word_11": "ink",
    "word_12": "bottom",
    "word_13": "coal",
    "word_14": "brown",
    "word_15": "gray"
  },
  {
    "List Name": "Bread",
    "word_1": "butter",
    "word_2": "food",
    "word_3": "eat",
    "word_4": "sandwich",
    "word_5": "rye",
    "word_6": "jam",
    "word_7": "milk",
    "word_8": "flour",
    "word_9": "jelly",
    "word_10": "dough",
    "word_11": "crust",
    "word_12": "slice",
    "word_13": "wine",
    "word_14": "loaf",
    "word_15": "toast"
  },
  {
    "List Name": "Chair",
    "word_1": "table",
    "word_2": "sit",
    "word_3": "legs",
    "word_4": "seat",
    "word_5": "couch",
    "word_6": "desk",
    "word_7": "recliner",
    "word_8": "sofa",
    "word_9": "wood",
    "word_10": "cushion",
    "word_11": "swivel",
    "word_12": "stool",
    "word_13": "sitting",
    "word_14": "rocking",
    "word_15": "bench"
  },
  {
    "List Name": "Cold",
    "word_1": "hot",
    "word_2": "snow",
    "word_3": "warm",
    "word_4": "winter",
    "word_5": "ice",
    "word_6": "wet",
    "word_7": "frigid",
    "word_8": "chilly",
    "word_9": "heat",
    "word_10": "weather",
    "word_11": "freeze",
    "word_12": "air",
    "word_13": "shiver",
    "word_14": "Arctic",
    "word_15": "frost"
  },
  {
    "List Name": "Doctor",
    "word_1": "nurse",
    "word_2": "sick",
    "word_3": "lawyer",
    "word_4": "medicine",
    "word_5": "health",
    "word_6": "hospital",
    "word_7": "dentist",
    "word_8": "physician",
    "word_9": "ill",
    "word_10": "patient",
    "word_11": "office",
    "word_12": "stethoscope",
    "word_13": "surgeon",
    "word_14": "clinic",
    "word_15": "cure"
  },
  {
    "List Name": "Foot",
    "word_1": "shoe",
    "word_2": "hand",
    "word_3": "toe",
    "word_4": "kick",
    "word_5": "sandals",
    "word_6": "soccer",
    "word_7": "yard",
    "word_8": "walk",
    "word_9": "ankle",
    "word_10": "arm",
    "word_11": "boot",
    "word_12": "inch",
    "word_13": "sock",
    "word_14": "smell",
    "word_15": "mouth"
  },
  {
    "List Name": "Fruit",
    "word_1": "apple",
    "word_2": "vegetable",
    "word_3": "orange",
    "word_4": "kiwi",
    "word_5": "citrus",
    "word_6": "ripe",
    "word_7": "pear",
    "word_8": "banana",
    "word_9": "berry",
    "word_10": "cherry",
    "word_11": "basket",
    "word_12": "juice",
    "word_13": "salad",
    "word_14": "bowl",
    "word_15": "cocktail"
  },
  {
    "List Name": "Girl",
    "word_1": "boy",
    "word_2": "dolls",
    "word_3": "female",
    "word_4": "young",
    "word_5": "dress",
    "word_6": "pretty",
    "word_7": "hair",
    "word_8": "niece",
    "word_9": "dance",
    "word_10": "beautiful",
    "word_11": "cute",
    "word_12": "date",
    "word_13": "aunt",
    "word_14": "daughter",
    "word_15": "sister"
  },
  {
    "List Name": "High",
    "word_1": "low",
    "word_2": "clouds",
    "word_3": "up",
    "word_4": "tall",
    "word_5": "tower",
    "word_6": "jump",
    "word_7": "above",
    "word_8": "building",
    "word_9": "noon",
    "word_10": "cliff",
    "word_11": "sky",
    "word_12": "over",
    "word_13": "airplane",
    "word_14": "dive",
    "word_15": "elevate"
  },
  {
    "List Name": "King",
    "word_1": "queen",
    "word_2": "England",
    "word_3": "crown",
    "word_4": "prince",
    "word_5": "George",
    "word_6": "dictator",
    "word_7": "palace",
    "word_8": "throne",
    "word_9": "chess",
    "word_10": "rule",
    "word_11": "subjects",
    "word_12": "monarch",
    "word_13": "royal",
    "word_14": "leader",
    "word_15": "reign"
  },
  {
    "List Name": "Man",
    "word_1": "woman",
    "word_2": "husband",
    "word_3": "uncle",
    "word_4": "lady",
    "word_5": "mouse",
    "word_6": "male",
    "word_7": "father",
    "word_8": "strong",
    "word_9": "friend",
    "word_10": "beard",
    "word_11": "person",
    "word_12": "handsome",
    "word_13": "muscle",
    "word_14": "suit",
    "word_15": "old"
  },
  {
    "List Name": "Mountain",
    "word_1": "hill",
    "word_2": "valley",
    "word_3": "climb",
    "word_4": "summit",
    "word_5": "top",
    "word_6": "molehill",
    "word_7": "peak",
    "word_8": "plain",
    "word_9": "glacier",
    "word_10": "goat",
    "word_11": "bike",
    "word_12": "climber",
    "word_13": "range",
    "word_14": "steep",
    "word_15": "ski"
  },
  {
    "List Name": "Music",
    "word_1": "note",
    "word_2": "sound",
    "word_3": "piano",
    "word_4": "sing",
    "word_5": "radio",
    "word_6": "band",
    "word_7": "melody",
    "word_8": "horn",
    "word_9": "concert",
    "word_10": "instrument",
    "word_11": "symphony",
    "word_12": "jazz",
    "word_13": "orchestra",
    "word_14": "art",
    "word_15": "rhythm"
  },
  {
    "List Name": "Needle",
    "word_1": "thread",
    "word_2": "pin",
    "word_3": "eye",
    "word_4": "sewing",
    "word_5": "sharp",
    "word_6": "point",
    "word_7": "prick",
    "word_8": "thimble",
    "word_9": "haystack",
    "word_10": "thorn",
    "word_11": "hurt",
    "word_12": "injection",
    "word_13": "syringe",
    "word_14": "cloth",
    "word_15": "knitting"
  },
  {
    "List Name": "River",
    "word_1": "water",
    "word_2": "stream",
    "word_3": "lake",
    "word_4": "Mississippi",
    "word_5": "boat",
    "word_6": "tide",
    "word_7": "swim",
    "word_8": "flow",
    "word_9": "run",
    "word_10": "barge",
    "word_11": "creek",
    "word_12": "brook",
    "word_13": "fish",
    "word_14": "bridge",
    "word_15": "winding"
  },
  {
    "List Name": "Rough",
    "word_1": "smooth",
    "word_2": "bumpy",
    "word_3": "road",
    "word_4": "tough",
    "word_5": "sandpaper",
    "word_6": "jagged",
    "word_7": "ready",
    "word_8": "coarse",
    "word_9": "uneven",
    "word_10": "riders",
    "word_11": "rugged",
    "word_12": "sand",
    "word_13": "boards",
    "word_14": "ground",
    "word_15": "gravel"
  },
  {
    "List Name": "Sleep",
    "word_1": "bed",
    "word_2": "rest",
    "word_3": "awake",
    "word_4": "tired",
    "word_5": "dream",
    "word_6": "wake",
    "word_7": "snooze",
    "word_8": "blanket",
    "word_9": "doze",
    "word_10": "slumber",
    "word_11": "snore",
    "word_12": "nap",
    "word_13": "peace",
    "word_14": "yawn",
    "word_15": "drowsy"
  },
  {
    "List Name": "Slow",
    "word_1": "fast",
    "word_2": "lethargic",
    "word_3": "stop",
    "word_4": "listless",
    "word_5": "snail",
    "word_6": "cautious",
    "word_7": "delay",
    "word_8": "traffic",
    "word_9": "turtle",
    "word_10": "hesitant",
    "word_11": "speed",
    "word_12": "quick",
    "word_13": "sluggish",
    "word_14": "wait",
    "word_15": "molasses"
  },
  {
    "List Name": "Soft",
    "word_1": "hard",
    "word_2": "light",
    "word_3": "pillow",
    "word_4": "plush",
    "word_5": "loud",
    "word_6": "cotton",
    "word_7": "fur",
    "word_8": "touch",
    "word_9": "fluffy",
    "word_10": "feather",
    "word_11": "furry",
    "word_12": "downy",
    "word_13": "kitten",
    "word_14": "skin",
    "word_15": "tender"
  },
  {
    "List Name": "Spider",
    "word_1": "web",
    "word_2": "insect",
    "word_3": "bug",
    "word_4": "fright",
    "word_5": "fly",
    "word_6": "arachnid",
    "word_7": "crawl",
    "word_8": "tarantula",
    "word_9": "poison",
    "word_10": "bite",
    "word_11": "creepy",
    "word_12": "animal",
    "word_13": "ugly",
    "word_14": "feelers",
    "word_15": "small"
  },
  {
    "List Name": "Sweet",
    "word_1": "sour",
    "word_2": "candy",
    "word_3": "sugar",
    "word_4": "bitter",
    "word_5": "good",
    "word_6": "taste",
    "word_7": "tooth",
    "word_8": "nice",
    "word_9": "honey",
    "word_10": "soda",
    "word_11": "chocolate",
    "word_12": "heart",
    "word_13": "cake",
    "word_14": "tart",
    "word_15": "pie"
  },
  {
    "List Name": "Thief",
    "word_1": "steal",
    "word_2": "robber",
    "word_3": "crook",
    "word_4": "burglar",
    "word_5": "money",
    "word_6": "cop",
    "word_7": "bad",
    "word_8": "rob",
    "word_9": "jail",
    "word_10": "gun",
    "word_11": "villain",
    "word_12": "crime",
    "word_13": "bank",
    "word_14": "bandit",
    "word_15": "criminal"
  },
  {
    "List Name": "Window",
    "word_1": "door",
    "word_2": "glass",
    "word_3": "pane",
    "word_4": "shade",
    "word_5": "ledge",
    "word_6": "sill",
    "word_7": "house",
    "word_8": "open",
    "word_9": "curtain",
    "word_10": "frame",
    "word_11": "view",
    "word_12": "breeze",
    "word_13": "sash",
    "word_14": "screen",
    "word_15": "shutter"
  }
]